table _Measures
	lineageTag: 425ca366-8b8e-4c46-8ada-33e93c0984c3

	measure 'Total Appointments' =
			
			COUNTROWS(Appointments)
		formatString: 0
		displayFolder: KPI
		lineageTag: 4bf2e2e4-91f0-4c5d-a060-9bc1e1ffbb35

	measure 'Completion Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Completed")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 10092593-b9e9-41b9-8104-877b48cec1a1

	measure 'No-Show Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "No Show")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 180269fc-6f4a-46fa-88ae-98f77207bc89

	measure 'Cancellation Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Cancelled")),
			    COUNTROWS(Appointments),
			    0
			)
		displayFolder: KPI
		lineageTag: 84b7a343-9bf8-4812-a8f6-144aaae32975

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wait Time (Min)' = ```
			
			CALCULATE(
			    AVERAGE(Rooms[Duration]),
			    Rooms[Is Waiting Room] = TRUE
			)
			
			    
			```
		displayFolder: KPI
		lineageTag: ee482928-3986-4239-9e12-5d60006c8f4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Duration' =
			
			CALCULATE(
			    AVERAGE(Appointments[Duration Without Infusion]),
			    Appointments[Status] = "Completed"
			)
		displayFolder: KPI
		lineageTag: 165cc250-6d40-44b7-b32b-d2f44acab8e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unique Patients' = DISTINCTCOUNT(Appointments[MRN])
		formatString: 0
		displayFolder: KPI
		lineageTag: 7939b46c-2af1-483a-88d7-87bb45d79422

	measure 'Appts MoM Change' = ```
			
			VAR _current = COUNTROWS(Appointments)
			VAR _prior = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATEADD('Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(_current - _prior, _prior, 0)
			```
		displayFolder: Time Intelligence
		lineageTag: c15f3f55-cf55-4215-abdf-059ff464f8f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts Rolling 3M Avg' = ```
			
			VAR _period = 
			    CALCULATETABLE(
			        VALUES('Date'[Month Year Sort]),
			        DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH)
			    )
			VAR _months = COUNTROWS(_period)
			VAR _visits = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH)
			    )
			RETURN
			    DIVIDE(_visits, _months)
			```
		displayFolder: Time Intelligence
		lineageTag: 3399bd66-c4e7-4e7e-bee4-a3e196591df0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NoShow Color' =
			
			IF(
			    [No-Show Rate] > 0.07, "#AE2012",
			    IF([No-Show Rate] > 0.05, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: f6b8c0ff-9303-46a5-af79-493a78c2bb8c

	measure 'Wait Time Color' =
			
			IF(
			    [Avg Wait Time (Min)] > 15, "#AE2012",
			    IF([Avg Wait Time (Min)] > 10, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: 2ca8f9b9-332c-4d3d-a0a2-66dbc2a161a8

	measure 'Appts YoY' = [Total Appointments] - [Appts PY]
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 33bdacbc-47a4-4d7a-8e1b-dc28f5667f00

	measure 'Appts PY' =
			
			CALCULATE(
			    [Total Appointments],
			    DATEADD('Date'[Date], -1, YEAR)
			)
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 5ca10299-1193-40c9-92e9-5abf35559713

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Avg Visit Duration (Min) Crossfilter' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed",
			    Rooms[Room Type] <> "Status",
			    CROSSFILTER(Appointments[Appointment ID], Rooms[Appointment ID], BOTH)
			)
		lineageTag: 3d39f862-24f2-42b6-9b8f-503e953c71a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Diff Format' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			
			VAR targetpercent = FORMAT([Appts YoY %], "0%")
			
			RETURN
				IF(
					targetpercent < 0, targetpercent & " " & down_arrow,
					targetpercent & " " & up_arrow
				)
		formatString: 0
		lineageTag: 90051758-2bb7-4ae8-9187-437677780dae

	measure 'MinMax Appointments' =
			
			VAR MaxValue =
			    CALCULATE(
			        MAXX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			VAR MinValue =
			    CALCULATE(
			        MINX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			RETURN
			    IF( MinValue = [Total Appointments] || MaxValue = [Total Appointments], [Total Appointments], BLANK() )
		formatString: 0
		lineageTag: 4f5e2b4b-2003-4900-a8e9-fa9a8d3b0c30

	measure 'Appts YoY %' =
			
			DIVIDE([Appts YoY], [Appts PY], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: 026f004c-fb0d-47a0-b0b0-ad60a43e1773

	measure 'YTD Appointments' = TOTALYTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: 20a70ba0-2698-47bc-8751-c319131e68ac

	measure 'Appts MTD' = TOTALMTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: 7187f7be-3c62-45d2-b318-214b65fecec2

	measure 'Appts QTD' = TOTALQTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: b924e533-2f7e-4e2d-bfcc-20afe16b8be6

	measure 'Completed Appointments' =
			
			CALCULATE(
			    [Total Appointments],
			    Appointments[Status] = "Completed"
			)
		formatString: 0
		displayFolder: Throughput
		lineageTag: a9e73190-8ad1-400e-b8bd-7355a06d8e4d

	measure 'Total Exam Minutes' =
			
			CALCULATE(
			    SUM(Rooms[Duration]),
			    Rooms[Room Type] = "Exam Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: caca88cc-415a-4f09-a723-ca974aac8d60

	measure 'Total Infusion Minutes' =
			
			CALCULATE(
			    SUM(Rooms[Duration]),
			    Rooms[Room Type] = "Infusion Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: b771183b-8cc4-44ef-868f-d237bb56b778

	measure 'Active Exam Rooms' =
			
			CALCULATE(
			    DISTINCTCOUNT(Rooms[Room]),
			    Rooms[Room Type] = "Exam Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: 0b5f0844-2193-480e-aa6e-75caae2821b7

	measure 'Exam Room Utilization %' = ```
			
			VAR _minutes = [Total Exam Minutes]
			VAR _rooms = [Active Exam Rooms]
			VAR _operatingDays = 
			    CALCULATE(
			        COUNTROWS('Date'),
			        'Date'[Day of Week] <= 5
			    )
			VAR _capacity = _rooms * _operatingDays * 480
			RETURN
			    DIVIDE(_minutes, _capacity, 0)
			```
		displayFolder: Resource Utilization
		lineageTag: 99b55be8-4de4-4e6b-b924-fd1fe4b43f37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Infusion Room Utilization %' = ```
			
			VAR _minutes = [Total Infusion Minutes]
			VAR _rooms = 
			    CALCULATE(
			        DISTINCTCOUNT(Rooms[Room]),
			        Rooms[Room Type] = "Infusion Room"
			    )
			VAR _operatingDays = 
			    CALCULATE(
			        COUNTROWS('Date'),
			        'Date'[Day of Week] <= 5
			    )
			VAR _capacity = _rooms * _operatingDays * 480
			RETURN
			    DIVIDE(_minutes, _capacity, 0)
			```
		displayFolder: Resource Utilization
		lineageTag: eabe29a3-5fc9-429d-b06e-cbc5c675bd17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Wait Time (Min)' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			RETURN
			    MEDIANX(FILTER(WaitByAppt, [@Wait] > 0), [@Wait])
			```
		displayFolder: Wait Time
		lineageTag: 5c16e4fe-9063-4779-973c-1822d92850ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P90 Wait Time (Min)' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			RETURN
			    PERCENTILEX.INC(FILTER(WaitByAppt, [@Wait] > 0), [@Wait], 0.9)
			```
		displayFolder: Wait Time
		lineageTag: aa7c430b-0b56-4058-8fe2-1496257d848c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Long Wait %' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			VAR _long = COUNTROWS(FILTER(WaitByAppt, [@Wait] > 20))
			VAR _total = COUNTROWS(WaitByAppt)
			RETURN
			    DIVIDE(_long, _total, 0)
			```
		displayFolder: Wait Time
		lineageTag: 2de42d9c-7916-47a1-aa9e-253bf1e736e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Appt Sparkline' = ```
			
			// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
			VAR LineColour = "%23118DFF"
			VAR PointColour = "white"
			VAR Defs = "<defs>
			    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
			        <stop stop-color='#118DFF' offset='0' />
			        <stop stop-color='#118DFF' offset='0.3' />
			        <stop stop-color='white' offset='1' />
			    </linearGradient>
			</defs>"
			// "Date" field used in this example along the X axis
			VAR XMinDate = MIN(Appointments[Appointment Date])
			VAR XMaxDate = MAX(Appointments[Appointment Date])
			
			// Obtain overall min and overall max measure values when evaluated for each date
			VAR YMinValue = MINX(Values(Appointments[Appointment Date]),CALCULATE([Total Appointments]))
			VAR YMaxValue = MAXX(Values(Appointments[Appointment Date]),CALCULATE([Total Appointments]))
			
			// Build table of X & Y coordinates and fit to 50 x 150 viewbox
			VAR SparklineTable = ADDCOLUMNS(
			    SUMMARIZE('Appointments',Appointments[Appointment Date]),
			        "X",INT(150 * DIVIDE(Appointments[Appointment Date] - XMinDate, XMaxDate - XMinDate)),
			        "Y",INT(50 * DIVIDE([Total Appointments] - YMinValue,YMaxValue - YMinValue)))
			
			// Concatenate X & Y coordinates to build the sparkline
			VAR Lines = CONCATENATEX(SparklineTable,[X] & "," & 50-[Y]," ", Appointments[Appointment Date])
			
			// Last data points on the line
			VAR LastSparkYValue = MAXX( FILTER(SparklineTable, Appointments[Appointment Date] = XMaxDate), [Y])
			VAR LastSparkXValue = MAXX( FILTER(SparklineTable, Appointments[Appointment Date] = XMaxDate), [X])
			
			// Add to SVG, and verify Data Category is set to Image URL for this measure
			VAR SVGImageURL = 
			    "data:image/svg+xml;utf8," & 
			    --- gradient---
			    "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & 
			     "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
			      stroke-width='0' points=' 0 50 " & Lines & 
			      " 150 150 Z '/>" &
			    --- Lines---
			    "<polyline 
			        fill='transparent' stroke='" & LineColour & "' 
			        stroke-linecap='round' stroke-linejoin='round' 
			        stroke-width='3' points=' " & Lines & 
			      " '/>" &
			    --- Last Point---
			        "<circle cx='"& LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='3' fill='" & PointColour & "' />" &
			        "</svg>"
			RETURN SVGImageURL
			```
		lineageTag: 6ccbb9ee-046d-4c6d-b0aa-da311c9f5da8

	measure _Selected_MinDate = ```
			
			VAR MinDate = [MinDate] - 1
			VAR MaxDate = [MaxDate] + 1 
			RETURN
			
			SWITCH(
			    [_Selected_Date],
			    "1W", MaxDate - 7,
			    "1M", EDATE(MaxDate, -1),
			    "3M", EDATE(MaxDate, -3),
			    "YTD", DATE(YEAR(MaxDate), 1, 1),
			    "1Y", EDATE(MaxDate, -12),
			    "All", MinDate
			)
			```
		formatString: General Date
		lineageTag: 77e7d3cc-4310-4fec-bce5-10fb690dadcd

	measure MinDate = ```
			
			CALCULATE(
			    MIN('Date'[Date]),
			    REMOVEFILTERS('Date'[Date])
			)
			
			```
		formatString: General Date
		lineageTag: e9e83b92-c19b-4261-88c6-b2cd58c7264b

	measure MaxDate = ```
			
			CALCULATE(
			    MAX('Date'[Date]),
			    REMOVEFILTERS('Date'[Date])
			)
			
			```
		formatString: General Date
		lineageTag: fc7b538f-28cd-48bc-85ce-d892ae637b5c

	measure _Selected_Date = SELECTEDVALUE('_Date_Selection'[Date Selection])
		lineageTag: 9828154f-fc77-4820-bc98-295cf7798137

	measure _Selected_Measure =
			
			SWITCH(
			    SELECTEDVALUE('_Measure_Selection'[Measure Selection]),
			    "Total Appointments", [Total Appointments],
			    "Average Duration", [Avg Duration]
			)
		lineageTag: b6eb526f-2283-4044-908e-10b0775c69cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Dates_Param =
			
			CALCULATE(
			    [_Selected_Measure],
			    KEEPFILTERS(
			        DATESBETWEEN(
			            'Date'[Date],
			            [_Selected_MinDate],
			            [MaxDate]
			        )
			    )
			)
		lineageTag: e2edf31d-2c08-4d86-974f-0971d7f6f068

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Selected_Moving_Average = SELECTEDVALUE(_Moving_Average_Selection[Days])
		formatString: 0
		lineageTag: 6f72c53f-0cb3-48f0-8c91-14ef57c57e5d

	measure _Moving_Average =
			
			AVERAGEX(
			    DATESINPERIOD(
			        'Date'[Date],
			        LASTDATE('Date'[Date]),
			        -[_Selected_Moving_Average],
			        DAY
			    ),
			    [_Selected_Measure]
			)
		lineageTag: f7c59a39-7f70-4abc-b6d5-1d8adfc03994

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Moving_Average_Dates_Param =
			
			IF(
			    ISBLANK([_Selected_Measure]),
			    BLANK(),
			
			    CALCULATE(
			        [_Moving_Average],
			        KEEPFILTERS(
			            DATESBETWEEN(
			                'Date'[Date],
			                [_Selected_MinDate],
			                [MaxDate]
			            )
			        )
			    )
			)
		lineageTag: e244da6b-eabe-48f0-adee-d06d53a9d613

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Selected_MinDate_PP = ```
			
			VAR MinDate = [MinDate] - 1
			VAR MaxDate = [_Selected_MinDate] - 1 
			RETURN
			
			SWITCH(
			    [_Selected_Date],
			    "1W", MaxDate - 7,
			    "1M", EDATE(MaxDate, -1),
			    "3M", EDATE(MaxDate, -3),
			    "YTD", DATE(YEAR(MaxDate), 1, 1),
			    "1Y", EDATE(MaxDate, -12),
			    "All", MinDate
			)
			```
		formatString: General Date
		lineageTag: 4e8244aa-4bfc-4940-81d9-b2b431269344

	measure _Dates_Param_PP =
			
			CALCULATE(
			    [_Selected_Measure],
			    KEEPFILTERS(
			        DATESBETWEEN(
			            'Date'[Date],
			            [_Selected_MinDate_PP],
			            [_Selected_MinDate]
			        )
			    )
			)
		lineageTag: 3cf8f843-1bf3-4cab-bd48-89c7572ee289

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Dates_Param_Delta = [_Dates_Param] - [_Dates_Param_PP]
		lineageTag: 7e1e6bdc-f6bc-4a70-828e-04a93e6b36fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Dates_Param_Delta %' = DIVIDE([_Dates_Param_Delta], [_Dates_Param_PP], 0)
		lineageTag: 05ae27d3-fbe5-4bd7-ae19-052a5451b0f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Selected_Measure_Text = SELECTEDVALUE('_Measure_Selection'[Measure Selection])
		lineageTag: be25999f-a21d-4dd6-91e2-e7e60f853e9e

	measure _PP_Reference_Label = ```
			
			
			VAR _Current = [_Dates_Param]
			VAR _LY = [_Dates_Param_PP]
			VAR _Growth = [_Dates_Param_Delta %]
			VAR NumOfDigits = 
			IFERROR(
			    LEN(
			        CONVERT(
			            INT([_Dates_Param]),
			            STRING
			        )
			    )
			    , 0)
			
			VAR Suffix = 
			".0" &
			SWITCH(
			    TRUE(),
			    NumOfDigits >= 13, "T",
			    NumOfDigits >= 10, "B",
			    NumOfDigits >= 7, "M",
			    NumOfDigits >= 4, "K",
			    ""
			)
			
			VAR Commas = 
			REPT(",",
			    SWITCH(
			        TRUE(),
			        NumOfDigits >= 13, "4",
			        NumOfDigits >= 10, "3",
			        NumOfDigits >= 7, "2",
			        NumOfDigits >= 4, "1",
			        "0"
			    )
			)
			
			VAR _Format = "#,##0" & Commas & Suffix & ";-#,##0" & Commas & Suffix
			
			RETURN
			IF(
			    _Growth <> 0,
			    "" &FORMAT(_Current - _LY, _Format)
			    &FORMAT(_Growth, " | 0.0% ▲; | 0.0% ▼;")& "", " ")
			```
		lineageTag: 6c953826-e2d8-4d78-b53b-a8aaa0d42854

	measure _Reference_Label_Font_Color =
			
			VAR label = [_Dates_Param_Delta]
			RETURN
			SWITCH(
			    TRUE(),
			    label > 0, "#038D96",
			    label < 0, "#A84545"
			)
		lineageTag: f86e9204-c8fc-4886-a662-6ba0a6545810

	measure _Reference_Label_Background_Color = ```
			
			VAR label = [_Dates_Param_Delta] 
			RETURN
			SWITCH(TRUE(),
			    label > 0 , "#E7F3F5", 
			    label < 0, "#F6EDED"
			    )
			```
		lineageTag: d6a1d65e-3d0f-4e21-9670-1de909cff4dd

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

