table _Measures
	lineageTag: 425ca366-8b8e-4c46-8ada-33e93c0984c3

	measure 'Total Appointments' =
			
			COUNTROWS(Appointments)
		formatString: 0
		displayFolder: KPI
		lineageTag: 4bf2e2e4-91f0-4c5d-a060-9bc1e1ffbb35

	measure 'Completion Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Completed")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 10092593-b9e9-41b9-8104-877b48cec1a1

	measure 'No-Show Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "No Show")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 180269fc-6f4a-46fa-88ae-98f77207bc89

	measure 'Cancellation Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Cancelled")),
			    COUNTROWS(Appointments),
			    0
			)
		displayFolder: KPI
		lineageTag: 84b7a343-9bf8-4812-a8f6-144aaae32975

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wait Time (Min)' = ```
			
			CALCULATE(
			    AVERAGE(Rooms[Duration]),
			    Rooms[Is Waiting Room] = TRUE
			)
			
			    
			```
		displayFolder: KPI
		lineageTag: ee482928-3986-4239-9e12-5d60006c8f4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Visit Duration (Min)' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed"
			)
		displayFolder: KPI
		lineageTag: 165cc250-6d40-44b7-b32b-d2f44acab8e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unique Patients' = DISTINCTCOUNT(Appointments[MRN])
		formatString: 0
		displayFolder: KPI
		lineageTag: 7939b46c-2af1-483a-88d7-87bb45d79422

	measure 'Avg Duration by Provider' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed"
			)
		lineageTag: 01660de4-ccac-40f1-93d4-5ee2929520e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts MoM Change' = ```
			
			VAR _current = COUNTROWS(Appointments)
			VAR _prior = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATEADD('Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(_current - _prior, _prior, 0)
			```
		displayFolder: Time Intelligence
		lineageTag: c15f3f55-cf55-4215-abdf-059ff464f8f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts Rolling 3M Avg' = ```
			
			VAR _period = 
			    CALCULATETABLE(
			        VALUES('Date'[Month Year Sort]),
			        DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH)
			    )
			VAR _months = COUNTROWS(_period)
			VAR _visits = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH)
			    )
			RETURN
			    DIVIDE(_visits, _months)
			```
		displayFolder: Time Intelligence
		lineageTag: 3399bd66-c4e7-4e7e-bee4-a3e196591df0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NoShow Color' =
			
			IF(
			    [No-Show Rate] > 0.07, "#AE2012",
			    IF([No-Show Rate] > 0.05, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: f6b8c0ff-9303-46a5-af79-493a78c2bb8c

	measure 'Wait Time Color' =
			
			IF(
			    [Avg Wait Time (Min)] > 15, "#AE2012",
			    IF([Avg Wait Time (Min)] > 10, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: 2ca8f9b9-332c-4d3d-a0a2-66dbc2a161a8

	measure 'Appts YoY' = [Total Appointments] - [Appts PY]
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 33bdacbc-47a4-4d7a-8e1b-dc28f5667f00

	measure 'Appts PY' =
			
			CALCULATE(
			    [Total Appointments],
			    DATEADD('Date'[Date], -1, YEAR)
			)
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 5ca10299-1193-40c9-92e9-5abf35559713

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Avg Visit Duration (Min) Crossfilter' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed",
			    Rooms[Room Type] <> "Status",
			    CROSSFILTER(Appointments[Appointment ID], Rooms[Appointment ID], BOTH)
			)
		lineageTag: 3d39f862-24f2-42b6-9b8f-503e953c71a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Diff Format' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR target = [Appts PY]
			VAR targetdiff = [Appts YoY]
			VAR targetpercent = FORMAT([Appts YoY Change], "0%")
			
			RETURN
				IF(
					targetdiff < 0, targetpercent & " " & down_arrow,
					targetpercent & " " & up_arrow
				)
		lineageTag: 90051758-2bb7-4ae8-9187-437677780dae

	measure 'MinMax Appointments' =
			
			VAR MaxValue =
			    CALCULATE(
			        MAXX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			VAR MinValue =
			    CALCULATE(
			        MINX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			RETURN
			    IF( MinValue = [Total Appointments] || MaxValue = [Total Appointments], [Total Appointments], BLANK() )
		formatString: 0
		lineageTag: 4f5e2b4b-2003-4900-a8e9-fa9a8d3b0c30

	measure 'Appts YoY %' =
			
			DIVIDE([Appts YoY], [Appts PY], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: 026f004c-fb0d-47a0-b0b0-ad60a43e1773

	measure 'YTD Appointments' = TOTALYTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: 20a70ba0-2698-47bc-8751-c319131e68ac

	measure 'Appts MTD' = TOTALMTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: 7187f7be-3c62-45d2-b318-214b65fecec2

	measure 'Appts QTD' = TOTALQTD([Total Appointments], 'Date'[Date])
		formatString: 0
		displayFolder: Throughput
		lineageTag: b924e533-2f7e-4e2d-bfcc-20afe16b8be6

	measure 'Completed Appointments' =
			
			CALCULATE(
			    [Total Appointments],
			    Appointments[Status] = "Completed"
			)
		formatString: 0
		displayFolder: Throughput
		lineageTag: a9e73190-8ad1-400e-b8bd-7355a06d8e4d

	measure 'Total Exam Minutes' =
			
			CALCULATE(
			    SUM(Rooms[Duration]),
			    Rooms[Room Type] = "Exam Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: caca88cc-415a-4f09-a723-ca974aac8d60

	measure 'Total Infusion Minutes' =
			
			CALCULATE(
			    SUM(Rooms[Duration]),
			    Rooms[Room Type] = "Infusion Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: b771183b-8cc4-44ef-868f-d237bb56b778

	measure 'Active Exam Rooms' =
			
			CALCULATE(
			    DISTINCTCOUNT(Rooms[Room]),
			    Rooms[Room Type] = "Exam Room"
			)
		formatString: 0
		displayFolder: Resource Utilization
		lineageTag: 0b5f0844-2193-480e-aa6e-75caae2821b7

	measure 'Exam Room Utilization %' = ```
			
			VAR _minutes = [Total Exam Minutes]
			VAR _rooms = [Active Exam Rooms]
			VAR _operatingDays = 
			    CALCULATE(
			        COUNTROWS('Date'),
			        'Date'[Day of Week] <= 5
			    )
			VAR _capacity = _rooms * _operatingDays * 480
			RETURN
			    DIVIDE(_minutes, _capacity, 0)
			```
		displayFolder: Resource Utilization
		lineageTag: 99b55be8-4de4-4e6b-b924-fd1fe4b43f37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Infusion Room Utilization %' = ```
			
			VAR _minutes = [Total Infusion Minutes]
			VAR _rooms = 
			    CALCULATE(
			        DISTINCTCOUNT(Rooms[Room]),
			        Rooms[Room Type] = "Infusion Room"
			    )
			VAR _operatingDays = 
			    CALCULATE(
			        COUNTROWS('Date'),
			        'Date'[Day of Week] <= 5
			    )
			VAR _capacity = _rooms * _operatingDays * 480
			RETURN
			    DIVIDE(_minutes, _capacity, 0)
			```
		displayFolder: Resource Utilization
		lineageTag: eabe29a3-5fc9-429d-b06e-cbc5c675bd17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Wait Time (Min)' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			RETURN
			    MEDIANX(FILTER(WaitByAppt, [@Wait] > 0), [@Wait])
			```
		displayFolder: Wait Time
		lineageTag: 5c16e4fe-9063-4779-973c-1822d92850ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P90 Wait Time (Min)' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			RETURN
			    PERCENTILEX.INC(FILTER(WaitByAppt, [@Wait] > 0), [@Wait], 0.9)
			```
		displayFolder: Wait Time
		lineageTag: aa7c430b-0b56-4058-8fe2-1496257d848c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Long Wait %' = ```
			
			VAR WaitByAppt = 
			    ADDCOLUMNS(
			        SUMMARIZE(Rooms, Appointments[Appointment ID]),
			        "@Wait", 
			            CALCULATE(
			                SUM(Rooms[Duration]),
			                Rooms[Is Waiting Room] = TRUE
			            )
			    )
			VAR _long = COUNTROWS(FILTER(WaitByAppt, [@Wait] > 20))
			VAR _total = COUNTROWS(WaitByAppt)
			RETURN
			    DIVIDE(_long, _total, 0)
			```
		displayFolder: Wait Time
		lineageTag: 2de42d9c-7916-47a1-aa9e-253bf1e736e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

