table _Measure_Selection
	lineageTag: a33d4b94-7cae-4dee-bf5f-c69959fe230f

	column 'Measure Selection'
		dataType: string
		lineageTag: ca326e74-1df2-4acb-8e16-a1a0a4d858d0
		summarizeBy: none
		sourceColumn: Measure Selection

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: a07ada1d-3946-4ce3-86b3-409ecda65912
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition _Measure_Selection = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCskvScxRcCwoyM/MK8lNzSspVtJRMlSK1YlWcixLLUpMT1VwKS1KLMnMzwNKGCnFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Selected Measure" = _t, Index = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Selected Measure", type text}, {"Index", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Selected Measure", "Measure Selection"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

