table _Measures
	lineageTag: 425ca366-8b8e-4c46-8ada-33e93c0984c3

	measure Placeholder = DATATABLE("Placeholder", STRING, {{"x"}})
		lineageTag: 41528c26-67b2-4439-ba1e-1f39159572c5

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

