table _Measures
	lineageTag: 425ca366-8b8e-4c46-8ada-33e93c0984c3

	measure 'Total Appointments' =
			
			COUNTROWS(Appointments)
		formatString: 0
		displayFolder: KPI
		lineageTag: 4bf2e2e4-91f0-4c5d-a060-9bc1e1ffbb35

	measure 'Completion Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Completed")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 10092593-b9e9-41b9-8104-877b48cec1a1

	measure 'No-Show Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "No Show")),
			    COUNTROWS(Appointments),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: KPI
		lineageTag: 180269fc-6f4a-46fa-88ae-98f77207bc89

	measure 'Cancellation Rate' =
			
			DIVIDE(
			    COUNTROWS(FILTER(Appointments, Appointments[Status] = "Cancelled")),
			    COUNTROWS(Appointments),
			    0
			)
		displayFolder: KPI
		lineageTag: 84b7a343-9bf8-4812-a8f6-144aaae32975

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wait Time (Min)' = ```
			
			CALCULATE(
			    AVERAGE(Rooms[Duration]),
			    Rooms[Is Waiting Room] = TRUE
			)
			
			    
			```
		displayFolder: KPI
		lineageTag: ee482928-3986-4239-9e12-5d60006c8f4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Visit Duration (Min)' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed"
			)
		displayFolder: KPI
		lineageTag: 165cc250-6d40-44b7-b32b-d2f44acab8e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unique Patients' = DISTINCTCOUNT(Appointments[MRN])
		formatString: 0
		displayFolder: KPI
		lineageTag: 7939b46c-2af1-483a-88d7-87bb45d79422

	measure 'Avg Duration by Provider' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed"
			)
		lineageTag: 01660de4-ccac-40f1-93d4-5ee2929520e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts MoM Change' = ```
			
			VAR _current = COUNTROWS(Appointments)
			VAR _prior = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATEADD('Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(_current - _prior, _prior, 0)
			```
		displayFolder: Time Intelligence
		lineageTag: c15f3f55-cf55-4215-abdf-059ff464f8f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts YoY Change' = ```
			
			VAR _current = COUNTROWS(Appointments)
			VAR _prior = 
			    CALCULATE(
			        COUNTROWS(Appointments),
			        DATEADD('Date'[Date], -1, YEAR)
			    )
			RETURN
			    DIVIDE(_current - _prior, _prior, 0)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: d9c47517-98e2-4c8d-80ae-2a926fe01c74

	measure 'Appts Rolling 3M Avg' =
			
			CALCULATE(
			    DIVIDE(COUNTROWS(Appointments), 3),
			    DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH)
			)
		displayFolder: Time Intelligence
		lineageTag: 3399bd66-c4e7-4e7e-bee4-a3e196591df0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NoShow Color' =
			
			IF(
			    [No-Show Rate] > 0.07, "#AE2012",
			    IF([No-Show Rate] > 0.05, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: f6b8c0ff-9303-46a5-af79-493a78c2bb8c

	measure 'Wait Time Color' =
			
			IF(
			    [Avg Wait Time (Min)] > 15, "#AE2012",
			    IF([Avg Wait Time (Min)] > 10, "#EE9B00", "#005F73")
			)
		displayFolder: Formating
		lineageTag: 2ca8f9b9-332c-4d3d-a0a2-66dbc2a161a8

	measure 'Appts YoY' = [Total Appointments] - [Appts PY]
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 33bdacbc-47a4-4d7a-8e1b-dc28f5667f00

	measure 'Avg Visit Duration (Min) Crossfilter' =
			
			CALCULATE(
			    AVERAGE(Appointments[Total Duration]),
			    Appointments[Status] = "Completed",
			    Rooms[Room Type] <> "Status",
			    CROSSFILTER(Appointments[Appointment ID], Rooms[Appointment ID], BOTH)
			)
		lineageTag: 3d39f862-24f2-42b6-9b8f-503e953c71a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts PY' =
			
			CALCULATE(
			    [Total Appointments],
			    DATEADD('Date'[Date], -1, YEAR)
			)
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 5ca10299-1193-40c9-92e9-5abf35559713

	measure 'Target Diff Format' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR target = [Appts PY]
			VAR targetdiff = [Appts YoY]
			VAR targetpercent = FORMAT([Appts YoY Change], "0%")
			
			RETURN
				IF(
					targetdiff < 0, targetpercent & " " & down_arrow,
					targetpercent & " " & up_arrow
				)
		lineageTag: 90051758-2bb7-4ae8-9187-437677780dae

	measure 'MinMax Appointments' =
			
			VAR MaxValue =
			    CALCULATE(
			        MAXX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			VAR MinValue =
			    CALCULATE(
			        MINX(
			            VALUES( 'Date'[Month] ),
			            [Total Appointments]
			        ),
			        ALLSELECTED('Date')
			    )
			RETURN
			    IF( MinValue = [Total Appointments] || MaxValue = [Total Appointments], [Total Appointments], BLANK() )
		formatString: 0
		lineageTag: 4f5e2b4b-2003-4900-a8e9-fa9a8d3b0c30

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

