table Appointments
	lineageTag: 6521c02d-db2f-4335-b17d-a107b832de70

	column 'Appointment ID'
		dataType: string
		lineageTag: 3d424c46-0814-4b17-8676-6607ced15d62
		summarizeBy: none
		sourceColumn: Appointment ID

		annotation SummarizationSetBy = Automatic

	column MRN
		dataType: string
		lineageTag: 89992ad2-0ce1-41fc-a620-c96bff81c743
		summarizeBy: none
		sourceColumn: MRN

		annotation SummarizationSetBy = Automatic

	column 'Provider ID'
		dataType: string
		lineageTag: 03b7f9c1-2baa-411e-8b74-58f72cc4cc30
		summarizeBy: none
		sourceColumn: Provider ID

		annotation SummarizationSetBy = Automatic

	column 'Appointment Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 12767d87-eaf3-4f37-96cf-ec4b165596a2
		summarizeBy: none
		sourceColumn: Appointment Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Visit Type'
		dataType: string
		lineageTag: 1eb11313-79ab-4913-8579-c754a14bbf25
		summarizeBy: none
		sourceColumn: Visit Type

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4d28dbae-55f1-4e37-90f7-21343495d250
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'New Patient Flag'
		dataType: int64
		formatString: 0
		lineageTag: 5610b0b5-8a5b-4a95-b208-676b2495b622
		summarizeBy: sum
		sourceColumn: New Patient Flag

		annotation SummarizationSetBy = Automatic

	column 'Infusion Flag'
		dataType: int64
		formatString: 0
		lineageTag: edbe3ec8-345a-45de-be13-6e3873988279
		summarizeBy: sum
		sourceColumn: Infusion Flag

		annotation SummarizationSetBy = Automatic

	column 'Urgent Flag'
		dataType: int64
		formatString: 0
		lineageTag: 547d5ad2-1165-48a4-bd84-71c496c9c37f
		summarizeBy: sum
		sourceColumn: Urgent Flag

		annotation SummarizationSetBy = Automatic

	column Room
		dataType: string
		lineageTag: ff2d6fd2-04e1-4117-a142-59807464d357
		summarizeBy: none
		sourceColumn: Room

		annotation SummarizationSetBy = Automatic

	column 'Room Type'
		dataType: string
		lineageTag: edad5ec1-8abf-4c3b-b266-afa39a6bf951
		summarizeBy: none
		sourceColumn: Room Type

		annotation SummarizationSetBy = Automatic

	column 'Room Timestamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: eff394c3-16e9-4a56-a6d7-ac51ef0478b3
		summarizeBy: none
		sourceColumn: Room Timestamp

		annotation SummarizationSetBy = Automatic

	column 'Room Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0105f7b1-3ef3-49aa-b5ca-eaaf0a4b6545
		summarizeBy: none
		sourceColumn: Room Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 964b6f00-7c5e-4157-af63-d21a2f5b8112
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column Sequence
		dataType: int64
		formatString: 0
		lineageTag: 402323cd-1ccb-4767-944d-ae9d7a79906a
		summarizeBy: sum
		sourceColumn: Sequence

		annotation SummarizationSetBy = Automatic

	partition Appointments = m
		mode: import
		source =
				let
				    Source = raw_Appointments,
				    #"Grouped Rows" = Table.Group(Source, {"Appointment ID"}, {{"Data", each _, type table [Appointment ID=nullable text, MRN=nullable text, Provider ID=nullable text, Appointment Date=nullable date, Visit Type=nullable text, Status=nullable text, New Patient Flag=nullable number, Infusion Flag=nullable number, Urgent Flag=nullable number, Room=nullable text, Room Type=nullable text, Room Timestamp=nullable datetime, Room Time=time, Duration=nullable number]}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Sequence", each Table.AddIndexColumn([Data], "Sequence", 1, 1)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom",{"Sequence"}),
				    #"Expanded Sequence" = Table.ExpandTableColumn(#"Removed Other Columns", "Sequence", {"Appointment ID", "MRN", "Provider ID", "Appointment Date", "Visit Type", "Status", "New Patient Flag", "Infusion Flag", "Urgent Flag", "Room", "Room Type", "Room Timestamp", "Room Time", "Duration", "Sequence"}, {"Appointment ID", "MRN", "Provider ID", "Appointment Date", "Visit Type", "Status", "New Patient Flag", "Infusion Flag", "Urgent Flag", "Room", "Room Type", "Room Timestamp", "Room Time", "Duration", "Sequence.1"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Sequence",{{"Appointment ID", type text}, {"MRN", type text}, {"Provider ID", type text}, {"Appointment Date", type date}, {"Visit Type", type text}, {"Status", type text}, {"New Patient Flag", Int64.Type}, {"Infusion Flag", Int64.Type}, {"Urgent Flag", Int64.Type}, {"Room", type text}, {"Room Type", type text}, {"Room Timestamp", type datetime}, {"Room Time", type time}, {"Duration", Int64.Type}, {"Sequence.1", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Sequence.1", "Sequence"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

